server {
    listen 80;
    server_name gacs.warp.land;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    listen 443 ssl;
    server_name gacs.warp.land;

    ssl_certificate     /etc/letsencrypt/live/gacs.warp.land/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gacs.warp.land/privkey.pem;

    resolver 127.0.0.11 valid=10s ipv6=off;
    client_max_body_size 10M;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    location /api/ {
        set $backend http://api:4000;
        proxy_pass $backend$request_uri;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        set $backend http://ui:3000;
        proxy_pass $backend$request_uri;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
