#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# We build a production env file locally, then ship it to the droplet as .env.
ENV_FILE=".env.production"
REPO_URL="git@github.com:wearereasonablepeople/gacs-poc.git"
BRANCH="simple"

banner "GACS Checker — deploy to gacs.warp.land"

# ── Stage 1: SSH connection & droplet state ───────────────────────────────
stage "Droplet — SSH access"
say "We deploy over SSH to the existing DigitalOcean droplet."
ask DROPLET_SSH   "SSH target (user@host):"          # e.g. root@gacs.warp.land
ask REMOTE_DIR    "Repo checkout dir on droplet:"    # e.g. /opt/gacs/app
ask REMOTE_DATA   "Data dir on droplet (SQLite lives here):"
: "${DROPLET_SSH:=root@gacs.warp.land}"
: "${REMOTE_DIR:=/opt/gacs/app}"
: "${REMOTE_DATA:=/opt/gacs/data}"
say ""
say "Testing the connection and showing what already runs on the droplet…"
if confirm "Run the connection check now?"; then
  ssh "$DROPLET_SSH" "echo connected as \$(whoami); docker --version || echo 'docker MISSING'; git --version || echo 'git MISSING'; echo '--- ports 80/443 ---'; (ss -tlnp 2>/dev/null | grep -E ':80|:443') || echo '(nothing listening yet)'; echo '--- containers ---'; docker ps --format '{{.Names}}\t{{.Image}}\t{{.Ports}}' 2>/dev/null || true" \
    || warn "SSH check failed — fix access (ssh $DROPLET_SSH) before continuing."
fi
note "gacs.warp.land must already point at this droplet (it did for the old stack)."
pause

# ── Stage 2: Provider / acquisition CTA ───────────────────────────────────
stage "Provider — acquisition CTA"
say "These fill the results email + thank-you screen. Empty ones are omitted."
ask PROVIDER_NAME "Provider name (shown in copy):"
ask CONTACT_URL   "Contact URL (blank to skip):"
ask CONTACT_EMAIL "Contact email (blank to skip):"
ask CONTACT_PHONE "Contact phone (blank to skip):"
write_env PROVIDER_NAME "$PROVIDER_NAME"
write_env CONTACT_URL   "$CONTACT_URL"
write_env CONTACT_EMAIL "$CONTACT_EMAIL"
write_env CONTACT_PHONE "$CONTACT_PHONE"

# ── Stage 3: Mail + core env ───────────────────────────────────────────────
stage "Mail — Gmail app password"
say "Results are sent from your Google Workspace mailbox via an app password."
open_url "https://myaccount.google.com/apppasswords"
step "Create (or reuse) a 16-char app password for 'Mail'."
ask        SMTP_USER         "SMTP user (the Gmail address):"
ask_secret SMTP_APP_PASSWORD "SMTP app password (hidden):"
ask        MAIL_FROM_NAME    "From display name:"
ask        REPLY_TO          "Reply-To (blank = SMTP user):"
ask        BCC_EMAIL         "Silent BCC for leads (blank to skip):"
: "${MAIL_FROM_NAME:=GACS Checker}"
write_env SMTP_HOST         "smtp.gmail.com"
write_env SMTP_PORT         "587"
write_env SMTP_USER         "$SMTP_USER"
write_env SMTP_APP_PASSWORD "$SMTP_APP_PASSWORD"
write_env MAIL_FROM_NAME    "$MAIL_FROM_NAME"
[[ -n "$REPLY_TO"  ]] && write_env REPLY_TO  "$REPLY_TO"
[[ -n "$BCC_EMAIL" ]] && write_env BCC_EMAIL "$BCC_EMAIL"
write_env PORT              "4000"
write_env DATABASE_PATH     "/data/submissions.sqlite"
write_env PUBLIC_WEB_ORIGIN "https://gacs.warp.land"
write_env GACS_DATA_DIR     "$REMOTE_DATA"

# ── Stage 4: Point the droplet at branch 'simple' ─────────────────────────
stage "Droplet — checkout branch '$BRANCH'"
say "Clone the repo if needed, then fetch and check out '$BRANCH'."
if confirm "Update the checkout at $REMOTE_DIR now?"; then
  ssh "$DROPLET_SSH" "REMOTE_DIR='$REMOTE_DIR' REPO_URL='$REPO_URL' BRANCH='$BRANCH' bash -s" <<'REMOTE'
set -euo pipefail
if [ ! -d "$REMOTE_DIR/.git" ]; then
  mkdir -p "$(dirname "$REMOTE_DIR")"
  git clone "$REPO_URL" "$REMOTE_DIR"
fi
cd "$REMOTE_DIR"
git fetch origin
git checkout "$BRANCH"
git pull --ff-only origin "$BRANCH"
echo "Now on: $(git rev-parse --abbrev-ref HEAD) @ $(git rev-parse --short HEAD)"
REMOTE
else
  warn "Skipped checkout — the deploy step below will use whatever is on the droplet."
fi
pause

# ── Stage 5: Ship env + deploy ─────────────────────────────────────────────
stage "Deploy — ship .env and start containers"
say "Copy the env file to the droplet and (re)build the production stack."
if confirm "Copy $ENV_FILE to $DROPLET_SSH:$REMOTE_DIR/.env ?"; then
  scp "$ENV_FILE" "$DROPLET_SSH:$REMOTE_DIR/.env"
  note "Shipped env with ${#WRITTEN_ENV[@]} keys."
fi
if confirm "Run 'docker compose -f docker-compose.prod.yml up -d --build' now?"; then
  ssh "$DROPLET_SSH" "REMOTE_DIR='$REMOTE_DIR' REMOTE_DATA='$REMOTE_DATA' bash -s" <<'REMOTE'
set -euo pipefail
cd "$REMOTE_DIR"
mkdir -p "$REMOTE_DATA"
docker compose -f docker-compose.prod.yml up -d --build
echo '--- containers ---'
docker compose -f docker-compose.prod.yml ps
REMOTE
fi
say ""
note "If the gateway can't start, TLS certs are missing at"
note "/etc/letsencrypt/live/gacs.warp.land/. Issue them once with certbot:"
note "  ssh $DROPLET_SSH 'certbot certonly --webroot -w /var/www/certbot -d gacs.warp.land'"
note "then re-run: docker compose -f docker-compose.prod.yml up -d --force-recreate gateway"
pause

# ── Stage 6: Smoke test ────────────────────────────────────────────────────
stage "Verify — hit the live site"
say "Checking the public endpoints over HTTPS…"
if command -v curl >/dev/null 2>&1; then
  code=$(curl -s -o /dev/null -w '%{http_code}' https://gacs.warp.land/api/health || echo 000)
  say "GET /api/health → HTTP $code"
  root=$(curl -s -o /dev/null -w '%{http_code}' https://gacs.warp.land/ || echo 000)
  say "GET /            → HTTP $root"
  if [[ "$code" == "200" && "$root" == "200" ]]; then
    say "${GREEN}Live.${RESET}"
  else
    warn "Not healthy yet — check: ssh $DROPLET_SSH 'cd $REMOTE_DIR && docker compose -f docker-compose.prod.yml logs --tail=50'"
  fi
fi
open_url "https://gacs.warp.land/"
step "Fill in a control point, submit with your email, confirm the mail arrives."

finish
